services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MNT}:/data
    environment:
      - CADDY_INGRESS_NETWORK=auth_net
    labels:
      caddy: (tinyauth_forwarder)
      caddy.forward_auth: tinyauth:3000
      caddy.forward_auth.uri: /api/auth/caddy
      caddy.forward_auth.copy_headers: "Remote-User Remote-Name Remote-Email Remote-Groups"
    networks:
      - auth_net
    deploy:
      mode: global

networks:
  auth_net:
    external: true