services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${MNT}:/data
    environment:
      - CADDY_DOCKER_MODE=server
      - CADDY_CONTROLLER_NETWORK=10.200.0.0/24
    labels:
      caddy: (tinyauth_forwarder)
      caddy.forward_auth: tinyauth:3000
      caddy.forward_auth.uri: /api/auth/caddy
      caddy.forward_auth.copy_headers: "Remote-User Remote-Name Remote-Email Remote-Groups"
    networks:
      - auth_net
      - caddy
      - caddy_controller
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        caddy_controlled_server:

  caddy_controller:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    networks:
      - caddy
      - caddy_controller
    environment:
      - CADDY_DOCKER_MODE=controller
      - CADDY_CONTROLLER_NETWORK=10.200.0.0/24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  caddy:
    driver: overlay
  caddy_controller:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "10.200.0.0/24"
  auth_net:
    external: true
