services:
  vikunja:
    container_name: vikunja
    image: vikunja/vikunja:latest
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${URL}
      VIKUNJA_DATABASE_HOST: ${DB_HOST}
      VIKUNJA_DATABASE_PASSWORD: ${DB_PASS}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: ${DB_USER}
      VIKUNJA_DATABASE_DATABASE: ${DB_NAME}
      VIKUNJA_SERVICE_JWTSECRET: ${SECRET}
      VIKUNJA_FILES_BASEPATH: /app/vikunja/files
    ports:
      - 3456:3456
    volumes:
      - ${MNT}/data:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default
      - tinyauth_net
    labels:
      caddy: ${URL}
      caddy.reverse_proxy: "{{ upstreams 3456 }}"
      caddy.import: tinyauth_forwarder *
      caddy.forward_auth: tinyauth:3000
      caddy.forward_auth.uri: /api/auth/caddy
    
  db:
    container_name: vikunja_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ${MNT}/db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s

networks:
  default:
    name: vikunja_network
    internal: true
    ipam:
      config:
        - subnet: 172.25.9.0/29
          gateway: 172.25.9.1
  tinyauth_net:
    external: true
